name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 30 02 * * * # 8:00 am IST every day
    - cron : 00 14 * * * # 7:30 pm IST every day
    - cron : 00 06 * * 1-5 # 11:30 pm IST Monday to Friday

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5.0.0

      - name: Install Nodejs and npm
        uses: actions/setup-node@v5.0.0
        with:
          node-version: '22'
          
      - name: Install Newman and htmlextra globally
        run: | 
             npm install -g newman
             npm install -g newman-reporter-htmlextra
             
      - name: run the Postman Collection with newman
        run: |
             newman run 'Inwarranty-flow Collection.postman_collection.json' \
             -e QA.postman_environment.json \
             -d testData.csv \
             -r cli,htmlextra

      - name : Newman Report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Newman Report
          path: newman/*.html
        
    
